GET http://localhost:3000/vehicles/1/credit HTTP/1.1

###

POST http://localhost:3000/vehicles  HTTP/1.1
content-type: application/json

{
    "parkingId": "1",
    "voucherId": "2",
    "categoryId": "3"
}

### 
POST http://localhost:3000/vehicles/24/deregister  HTTP/1.1
content-type: application/json

{

}